Run Initial.openBrowser "http://3.8.203.160", "removeitem"


Run LoginOrRegister.register "test@eggplant.com", "Keysight123"


to browser url
	DoubleClick "chromeIcon"
	WaitFor 8.0, "refresh"
	TypeText url
end browser

Run browser ("https://www.google.com")


to apiCall search
	put codeAPI(url:"https://www.google.com/search?q=" & search) into result
	return result.httpmethod
end apiCall


Log apiCall ("keysight")