Click  "Generic Camera View Controls/MoveForward5mButton"
Click  "Generic Camera View Controls/MoveForward1mButton"
Click  "Generic Camera View Controls/MoveForward1mButton"
Wait 1

Click "CW Camera Icons Positions/CameraIconCWRecordGradeUTS"
Wait 1
Click {Image:"CW Inspection Attributes/UnableToSurveyCheckBox", WaitFor:4.8}
Click "CW Inspection Attributes/CommentsDropDownSelector"
Click  "Generic UTSResonOptions/RequestInspectorAssignmentButtonUTS - No Video Footage"
click "CW Inspection Attributes/InspectionPanelSaveButton"