Click "Generic Camera View Controls/MoveForward5mButton"
Wait 1

Click   "CW Camera Icons Positions/CameraIconCWRecordGrade4"
Wait 1
Click "CW Inspection Attributes/GradeDropdownSelector"
Click  "Generic Grades/Grade4Option"
Click "CW Inspection Attributes/PrimarySurfaceTypeDropDownSelector"
ScrollWheelDown 6
Click "CW Primary Surface Types/NaturalStonePrimarySurfaceTypeOption"
click "CW Inspection Attributes/DamageAreaDropDownSelector"
Click "Generic DamageAreaValues/25% to 50%"
Click  "CW Primary Damage Type/EdgeBreakingPrimaryDamageType"
Click  "CW Secondary Damage Type/PotholesSecondaryDamageType"
Click "CW Inspection Attributes/InspectionPanelSaveButton"


