Click  "Generic Camera View Controls/MoveForward5mButton"
Click  "Generic Camera View Controls/MoveForward1mButton"
Click  "Generic Camera View Controls/MoveForward1mButton"
Wait 1

click  "CW Camera Icons Positions/CameraIconCWRecordGrade5"
Wait 1
Click "CW Inspection Attributes/GradeDropdownSelector"
Click  "Generic Grades/Grade5Option"
Click "CW Inspection Attributes/PrimarySurfaceTypeDropDownSelector"
ScrollWheelDown 6
Click  "CW Primary Surface Types/HighFrictionSurfacingPrimarySurfaceTypeOption"
click "CW Inspection Attributes/DamageAreaDropDownSelector"
Click  "Generic DamageAreaValues/75% to 100%"
Click "CW Inspection Attributes/NotesDropdownSelector"
Click "GenericNotesOptions/DamagesAtTheSideOfRoad"
Click  "CW Primary Damage Type/ShovingPrimaryDamageType"
Click  "CW Secondary Damage Type/RuttingSecondaryDamageType"
Click "CW Inspection Attributes/InspectionPanelSaveButton"





