
Click "Generic Camera View Controls/MoveForward5mButton"
Wait 1

Click  "CW Camera Icons Positions/CameraIconCWRecordGrade3"
Wait 2
Click "CW Inspection Attributes/GradeDropdownSelector"
Click "Generic Grades/Grade3Option"
Click "CW Inspection Attributes/PrimarySurfaceTypeDropDownSelector"
ScrollWheelDown 2
Click  "CW Primary Surface Types/ModularPrimarySurfaceTypeOption"
Click  "CW Inspection Attributes/SecondarySurfaceTypeDropDownSelector"
Click "CW Secondary Surface Type/ConcreteSecondarySurfaceTypeOptions"
click "CW Inspection Attributes/DamageAreaDropDownSelector"
Click  "Generic DamageAreaValues/5% to 25%"
Click  "CW Primary Damage Type/IronworkMissingPrimaryDamageType"
Click  "CW Secondary Damage Type/VegitationSecondaryDamageType"
Click "CW Inspection Attributes/InspectionPanelSaveButton"
