OpenMyIncidents
ValidateIncidents
CloseMyIncident


on OpenMyIncidents
	Click text:"My Incidents"
	WaitFor 20, text:"Search"
end OpenMyIncidents

On ValidateIncidents
	Click FoundImageLocation()
	waitfor 20 ,(text:"Denise Smith"),( text:"Carmen Wang")
End ValidateIncidents

On CloseMyIncident
	Click "ConfirmButton"
	WaitFor 20.0, "ConfirmIncidentpopup"
	Click "YesButton"
	wait 5
End CloseMyIncident