Click  "FW Assignment Camera Positions/Grade 2 LH FW"
Click  "FW Inspection Attribuites/GradeDropDown Selector"
Click "Generic Grades/Grade2Option"
Click "FW Inspection Attribuites/PrimarySurfaceTypeDropDownSelector"
ScrollWheelDown 1
Click "FW Primary Surface Types/ConcretePrimarySurfaceType"
Click "FW Inspection Attribuites/DamageAreaDropDownSelector"
Click "Generic DamageAreaValues/Less than 5%"
Click "FW Priamry Damage Types/SpotdefectsPrimaryDamageType"
Click "FW Priamry Damage Types/FrettingPrimaryDamageType"
Click "FW Secondary Damage Types/PatchingSecondaryDamageType"
Click "FW Inspection Attribuites/FW InspectionPanelSaveButton"

