Click "AddNewMapButton"
Click "MapsetNameField"
TypeText "EggplantCWMapset"
Click "VideoPhotoDatasetName"
TypeText "Testing"
DoubleClick "VideoPhotoDatasetYearField"
TypeText "Banes2021"
Click "SideScrollBar"
Click "SideScrollBar"
Click "SideScrollBar"
Click "SideScrollBar"
Click "SideScrollBar"
Click "SideScrollBar"
Click "SideScrollBar"
Click "SideScrollBar"
Click "SideScrollBar"
Click "SideScrollBar"
Click "LocalAuthorityDropDownSelector"
Click  "BanesCWLAOption"
Click "InspectionTypeDropDownSelector"
Click "CarriagewayInspectionOption"
Click "MapsetTemplateDropDownSelector"
Click "GaistCWTemplateOption"
Click "SideScrollBar"
Click "SideScrollBar"
Click "TeamsDropDownSelector"
Click "Team3Option"
Click "AddButton"
Click "SubmissionCheckTickBox"
Click "SaveButton"







