to cleanUp
	typetext altKey,F4
	set the SearchRectangle to empty
	StopMovie
end cleanUp

to logout
	Click "UserIcon"
	waitFor 10, text:"Sign Out", caseSensitive: true
	Click FoundImageLocation()
	
	waitFor 20, text:"Are you sure you"
	Click text:"OK"
	
	waitFor 10, text:"Log On", caseSensitive: true	
end logout

to homeScreen
	Click "homeMenu"
	waitFor 10, "HomeButton"
	Click FoundImageLocation()
end homeScreen

